# Generated by Django 4.0.4 on 2022-11-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
